config/routes.rb
Rails.application.routes.draw do
  resources :carts
  get 'users/mypage/edit', to: 'users#edit'
  get 'users/mypage', to: 'users#mypage'
  patch '/users/mypage', to: 'users#update'
  devise_for :admin_users
  devise_for :users
  resources :products do
    resources :reviews, only: [:create, :update, :destroy]
    member do
      post :like
    end
  end
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :carts
  acts_as_liker
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def mypage
    @likes = current_user.likees(Product)
  end

  def update
    current_user.update(user_params)

    redirect_to users_mypage_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :postal_code, :address, :phone)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with(model: current_user, local: true, url: users_mypage_path) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/mypage.html.erb
<%= current_user.name %>
<%= current_user.postal_code %>
<%= current_user.address %>
<%= current_user.phone %>

<% @likes.each do |like| %>
    <%= like.name %>
    <%= like.price %>
<% end %>

<%= link_to 'Edit', users_mypage_edit_path %> 

<%= link_to 'Password & Email Edit', edit_user_registration_path %>